func foo() {
  sum := 0;

  i := 0;

  for {
    sum += i;
    i++;

    if (i == 10) {
      return sum;
    }
  }

  return sum; // TODO should be error because this is unreachable
};

return foo(); // #error
